// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ClientBody from "./ClientBody";
// import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <head>
//         <Script
//           crossOrigin="anonymous"
//           src="//unpkg.com/same-runtime/dist/index.global.js"
//         />
//       </head>
//       <body suppressHydrationWarning className="antialiased">
//         <ClientBody>{children}</ClientBody>
//       </body>
//     </html>
//   );
// }
import { UserModeProvider } from "@/context/UserModeContext";
import type { Metadata } from "next";
import { CartProvider } from "@/context/CartContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";
import Navbar from "@/components/Navbar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SafeCart+",
  description: "Inclusive. Intelligent. Secure. Retail AI Assistant.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <meta name="theme-color" content="#ffffff" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Inclusive, AI-powered retail experience. Adaptive, secure, neuro-accessible shopping." />

        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
      </head>
      <body suppressHydrationWarning className="antialiased">
        <CartProvider>
          <UserModeProvider> {/* 👈 wrap all children */}
            <ClientBody>
              <Navbar />
              {children}
            </ClientBody>
          </UserModeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
